server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: APIGateway

  cloud:
    gateway:
      routes:
        - id: ListingService
          uri: lb://ListingService
          predicates:
            - Path=/api/listing/**

        - id: SecurityService
          uri: lb://SecurityService
          predicates:
            - Path=/auth/**
  main:
    web-application-type: reactive


